### ISSUE TITLE
Light/Full use same config.json will make Full use Light's folder

### ISSUE THREAD

**Issue by tlightsky** [HyperspaceApp/Hyperspace.app#6]
```
Hyperspace Daemon v0.2.2
Git Revision 4ea4096f6
Loading...
(0/6) Loading hsd...
(1/6) Loading gateway...
(2/6) Loading consensus...
(3/6) Loading transaction pool...
goroutine 1 [running]:
runtime/debug.Stack(0x4466ee, 0x0, 0xc0001dc0c8)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0xae
runtime/debug.PrintStack()
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:16 +0x29
github.com/HyperspaceApp/Hyperspace/build.Critical(0xc0001dc3c8, 0x2, 0x2)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/build/critical.go:16 +0x9a
github.com/HyperspaceApp/Hyperspace/persist.(*Logger).Critical(0xc00018f4c0, 0xc0001dc3c8, 0x2, 0x2)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/persist/log.go:37 +0xd3
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).computeConsensusChange(0xc000166780, 0xc000356b60, 0x0, 0x0, 0x0, 0xc000390100, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:49 +0x1112
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).managedInitializeSubscribe.func2(0xc000356b60, 0xcbb858, 0xc000356b60)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:178 +0x19a
github.com/HyperspaceApp/Hyperspace/vendor/github.com/coreos/bbolt.(*DB).View(0xc00010e780, 0xc0001dcf30, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/vendor/github.com/coreos/bbolt/db.go:708 +0x97
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).managedInitializeSubscribe(0xc000166780, 0xd915a0, 0xc000eea000, 0xa9fa2bff6c4ac0d, 0x695e36ba43cdf1e7, 0x4975cc0d5fa8882b, 0xaac654f26ff2b03c, 0xc000ee2960, 0x0, 0x0, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:170 +0x3e8
github.com/HyperspaceApp/Hyperspace/modules/consensus.(*ConsensusSet).ConsensusSetSubscribe(0xc000166780, 0xd915a0, 0xc000eea000, 0xa9fa2bff6c4ac0d, 0x695e36ba43cdf1e7, 0x4975cc0d5fa8882b, 0xaac654f26ff2b03c, 0xc000ee2960, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/consensus/subscribe.go:227 +0xf8
github.com/HyperspaceApp/Hyperspace/modules/transactionpool.(*TransactionPool).initPersist(0xc000eea000, 0xc000eea000, 0x50)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/transactionpool/persist.go:183 +0x94e
github.com/HyperspaceApp/Hyperspace/modules/transactionpool.New(0xda0e20, 0xc000166780, 0xd9e1c0, 0xc0000d8840, 0xc00067c000, 0x50, 0x0, 0x0, 0x0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/modules/transactionpool/transactionpool.go:104 +0x142
main.(*Server).loadModules(0xc0000d86e0, 0xcbbef8, 0xc0000446c0)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/server.go:513 +0x2783
main.startDaemon(0x0, 0x0, 0xc0000500cb, 0xe, 0xc0000520db, 0x5, 0xc00005010c, 0x5, 0x0, 0xc00005211a, ...)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/daemon.go:268 +0x2ca
main.startDaemonCmd(0xc000115680, 0xc0000aca50, 0x0, 0x5)
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/daemon.go:322 +0x1b4
github.com/spf13/cobra.(*Command).execute(0xc000115680, 0xc000088010, 0x5, 0x7, 0xc000115680, 0xc000088010)
	/Users/mark/.go/src/github.com/spf13/cobra/command.go:766 +0x2d3
github.com/spf13/cobra.(*Command).ExecuteC(0xc000115680, 0xc821db, 0xf, 0xc0001568c0)
	/Users/mark/.go/src/github.com/spf13/cobra/command.go:852 +0x304
github.com/spf13/cobra.(*Command).Execute(0xc000115680, 0x1366018, 0xc6f695)
	/Users/mark/.go/src/github.com/spf13/cobra/command.go:800 +0x32
main.main()
	/Users/mark/.go/src/github.com/HyperspaceApp/Hyperspace/cmd/hsd/main.go:197 +0x7ee
Critical error: getBlockMap failed in computeConsensusChange: requested item does not exist
Please submit a bug report here: https://github.com/HyperspaceApp/Hyperspace/issues
requested item does not exist

```

**Comment by tlightsky** [comment]
resolved by new folder for light/full ui
